config/routes.rb
Rails.application.routes.draw do
  get 'bmi',to: "bmi#index"
  post 'bmi/result',to: "bmi#result"
  devise_for :users
  resources :keyword_mappings
  resources :push_messages, only: [:new, :create]
  resources :rent_stuff
  resources :candidates do
    member do
      post :vote
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'kamigoo#eat'
  get '/kamigoo/eat', to: 'kamigoo#eat'
  get '/kamigoo/request_headers', to: 'kamigoo#request_headers'
  get '/kamigoo/request_body', to: 'kamigoo#request_body'
  get '/kamigoo/response_headers', to: 'kamigoo#response_headers'
  get '/kamigoo/response_body', to: 'kamigoo#show_response_body'
  
  get '/kamigoo/sent_request', to: 'kamigoo#sent_request'
  get '/kamigoo/sent_request1', to: 'kamigoo#sent_request1'
  
  post '/kamigoo/webhook', to: 'kamigoo#webhook'
end

app/models/candidate.rb
class Candidate < ApplicationRecord
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :find_candidate, only: [:edit, :update, :destroy, :vote, :show]

  
  def index 
    @candidates = Candidate.all.order(:id)
  end

  def new
    @candidate = Candidate.new
  end
  
  def show
  end
  
  def vote
    @candidate.increment(:votes)
    @candidate.save
    redirect_to candidates_path, notice: "完成投票!"
  end
  
  def create
    @candidate = Candidate.new(candidate_params)
    
    if @candidate.save
      # 成功
      redirect_to candidates_path, notice: "新增候選人成功!"
    else
      # 失敗
      render :new
    end
  end
  
  def edit
  end
  
  def update    
    if @candidate.update_attributes(candidate_params)
      # 成功
      redirect_to candidates_path, notice: "資料更新成功!"
    else
      #失敗
      render :edit
    end
  end
  
  def destroy
    @candidate.destroy if @candidate
    redirect_to candidates_path, notice: "候選人資料已刪除!"
  end
  
  private
  def candidate_params
    params.require(:candidate).permit(:name, :age, :party, :politics )
  end
  
  def find_candidate
    @candidate = Candidate.find_by(id: params[:id])
  end
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/_candidate.html.erb
<tr>
  <td><%= link_to "投給這位", vote_candidate_path(candidate), method: :post, data: { confirm: "確認要投給這位候選人嗎!?" }, class:"btn btn-danger btn-xs" %></td>
  <td><%= candidate.name %>(年齡：<%= candidate.age %> 歲)</td>
  <td><%= candidate.party %></td>
  <td><%= candidate.politics %></td>
  <td><%= candidate.votes %></td>
  <td>
    <%= link_to "編輯", edit_candidate_path(candidate) %>
    <%= link_to "刪除", candidate_path(candidate), method: :delete, data: { confirm: "確認刪除" } %>
  </td>
</tr>

app/views/candidates/_form.html.erb
<%= simple_form_for(@candidate) do |f| %>
  <%= f.input :name,label: "姓名" %>

  <%= f.input :age,label: "年齡" %>

  <%= f.input :party,label: "政黨" %>

  <%= f.input :politics,label: "政見" %>

  <%= f.submit %>

<% end %>

<br />
<%= link_to "回候選人列表", candidates_path %>

app/views/candidates/_form_old.html.erb
<%= form_for(@candidate) do |f| %>
  <%= f.label :name, "姓名" %>
  <%= f.text_field :name %> <br />

  <%= f.label :age, "年齡" %>
  <%= f.text_field :age %> <br />

  <%= f.label :party, "政黨" %>
  <%= f.text_field :party %> <br />

  <%= f.label :politics, "政見" %>
  <%= f.text_area :politics %> <br />

  <%= f.submit %>

<% end %>

<br />
<%= link_to "回候選人列表", candidates_path %>

app/views/candidates/edit.html.erb
<h1>編輯候選人</h1>

<%= render "form" %>

app/views/candidates/index.html.erb
<h1>候選人列表</h1>

<%= link_to "新增候選人", new_candidate_path %>

<table class="table table-hover table-bordered table-sm table-striped">
 <thead class="thead-light text-center">
   <tr>
     <th>投票</th>
     <th>候選人姓名</th>
     <th>政黨</th>
     <th>政見</th>
     <th>得票數</th>
     <th>處理</th>
   </tr>
 </thead>
 <tbody class="text-center">
   <%= render @candidates %>
 </tbody>
</table>

app/views/candidates/new.html.erb
<h1>新增候選人</h1>

<%= render "form" %>

app/views/candidates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>id:</strong>
  <%= @candidate.id %>
</p>

<p>
  <strong>name:</strong>
  <%= @candidate.name %>
</p>

<p>
  <strong>party:</strong>
  <%= @candidate.party %>
</p>

<p>
  <strong>age:</strong>
  <%= @candidate.age %>
</p>

<p>
  <strong>politics:</strong>
  <%= @candidate.politics %>
</p>

<p>
  <strong>votes:</strong>
  <%= @candidate.votes %>
</p>

<%= link_to 'Edit', edit_candidate_path(@candidate) %> |
<%= link_to 'Back', candidates_path %>